const dotenv = require("dotenv");
dotenv.config();

module.exports = {
  TELEGRAM_BOT_TOKEN_BINANCE_AUTOTRADER: process.env.TELEGRAM_BOT_TOKEN_BINANCE_AUTOTRADER,
  TELEGRAM_BOT_TOKEN_BINANCE_FVG: process.env.TELEGRAM_BOT_TOKEN_BINANCE_FVG,
  TELEGRAM_BOT_TOKEN_BINANCE_MKT_ORDER_MULTI_USER: process.env.TELEGRAM_BOT_TOKEN_BINANCE_MKT_ORDER_MULTI_USER,
  TELEGRAM_BOT_TOKEN_BYBIT_AUTOTRADER: process.env.TELEGRAM_BOT_TOKEN_BYBIT_AUTOTRADER,
  TELEGRAM_BOT_TOKEN_BYBIT_FVG: process.env.TELEGRAM_BOT_TOKEN_BYBIT_FVG,
  TELEGRAM_BOT_TOKEN_BYBIT_MKT_ORDER_MULTI_USER: process.env.TELEGRAM_BOT_TOKEN_BYBIT_MKT_ORDER_MULTI_USER,
};
